export * from './Favorite/Favorite'
export * from './Home/Home'
export * from './MyProfile/MyProfile'
export * from './NewPost/NewPost'
export * from './PostComments/PostComments'
export * from './Settings/Settings'
